Do not allow codecov rerun without PR number
When triggering codecov re-run on the PR, Github does not send in the pull request number, and as a result the code coverage check is skipped. So when that happens on the PR check, we should fail the build instead of allowing it to skip the coverage check.

Signed-off-by: Lin Guo <linsword13@gmail.com>

diff --git a/share/ramble/qa/run-unit-tests b/share/ramble/qa/run-unit-tests
--- a/share/ramble/qa/run-unit-tests
+++ b/share/ramble/qa/run-unit-tests
@@ -89,6 +89,11 @@ if [[ "$UNIT_TEST_COVERAGE" == "true" ]]; then
 fi
 
 if [[ "$PUSH_CODECOV" ]]; then
+  if [[ "$TRIGGER_NAME" == Codecov-PR* && -z "$PR_NUMBER" ]]; then
+    echo "Error: PR_NUMBER is not set for Codecov PR trigger ($TRIGGER_NAME)."
+    exit 1
+  fi
+
   if [[ -z "$COMMIT_SHA" ]]; then
     export COMMIT_SHA=`git -C $(dirname $0) log -n 1 --format="%H"`
   fi
